"use client";
import { useEffect, useState } from "react";
import { BookOpen, Menu } from "lucide-react";
import { useSidebar } from "@/components/ui/Sidebar";
import { useNavigationGuard } from "@/lib/useNavigationGuard";
import { fetchConfig, startGenerateStory, previewHistoryFile, type AppConfig } from "@/lib/api";
import { LogStream } from "@/components/LogStream";

type OutlineView = "outline" | "json";

interface StorySegment { id: number; title: string; description: string }
interface StoryOutline { title: string; premise: string; genre: string; language: string; durationMin: number; segments: StorySegment[] }

function Section({ num, title, children }: { num: string; title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-xl border border-gray-800 bg-gray-900/40 overflow-hidden">
      <div className="flex items-center gap-3 px-4 py-3 border-b border-gray-800/60">
        {num && <span className="text-xs font-mono text-gray-600 select-none">{num}</span>}
        <span className="text-sm font-semibold text-gray-200">{title}</span>
      </div>
      <div className="p-4 space-y-3">{children}</div>
    </div>
  );
}

function buildPreviewOutline(title: string, premise: string, genre: string, language: string, duration: number, segCount: number): StoryOutline {
  const placeholderTitles = ["Opening", "Rising tension", "Discovery", "Confrontation", "Resolution", "Aftermath", "The twist", "Denouement", "Epilogue", "Closing"];
  const segments = Array.from({ length: segCount }, (_, i) => ({
    id: i + 1,
    title: placeholderTitles[i % placeholderTitles.length],
    description: "Segment content will be generated by AI.",
  }));
  return { title: title || "Untitled Story", premise: premise || "", genre, language, durationMin: duration, segments };
}

function parseStoryJson(data: Record<string, unknown>): StoryOutline | null {
  try {
    const title = data.title as string ?? "";
    const premise = (data.premise ?? data.logline ?? "") as string;
    const genre = (data.genre ?? "") as string;
    const language = (data.language ?? "English") as string;
    const rawSegs: Array<{ segment_id?: number; title?: string; target_text?: string; summary?: string }> =
      (data.segments as Array<{ segment_id?: number; title?: string; target_text?: string; summary?: string }>) ?? [];
    const segments = rawSegs.map(s => ({
      id: s.segment_id ?? 0,
      title: s.title ?? `Segment ${s.segment_id}`,
      description: (s.summary ?? s.target_text ?? "").slice(0, 120),
    }));
    const durationMin = Math.round((segments.reduce((a, s) => a + s.description.split(/\s+/).length, 0) / 130));
    return { title, premise, genre, language, durationMin, segments };
  } catch { return null; }
}

export default function StoryPage() {
  const { setOpen: setSidebarOpen } = useSidebar();
  const [cfg, setCfg] = useState<AppConfig | null>(null);
  const [jobId, setJobId] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  useNavigationGuard(busy);

  const [title, setTitle] = useState("");
  const [premise, setPremise] = useState("");
  const [genre, setGenre] = useState("Horror");
  const [language, setLanguage] = useState("English");
  const [duration, setDuration] = useState(3);
  const [segments, setSegments] = useState(5);
  const [outputPath, setOutputPath] = useState("generated_story.json");
  const [outlineView, setOutlineView] = useState<OutlineView>("outline");
  const [generatedOutline, setGeneratedOutline] = useState<StoryOutline | null>(null);
  const [generatedJson, setGeneratedJson] = useState<string>("");

  useEffect(() => { fetchConfig().then(setCfg); }, []);

  // Build a live preview outline from current inputs
  const previewOutline = buildPreviewOutline(title, premise, genre, language, duration, segments);
  const displayOutline = generatedOutline ?? previewOutline;
  const isDraft = !generatedOutline;

  async function loadGeneratedStory() {
    try {
      const data = await previewHistoryFile(outputPath);
      const parsed = parseStoryJson(data as Record<string, unknown>);
      if (parsed) {
        setGeneratedOutline(parsed);
        setGeneratedJson(JSON.stringify(data, null, 2));
      }
    } catch { /* file may not exist yet */ }
  }

  async function submit(e: React.FormEvent) {
    e.preventDefault();
    if (!title.trim()) return;
    setBusy(true);
    setGeneratedOutline(null);
    setGeneratedJson("");
    const jid = await startGenerateStory({
      title, premise, genre, language,
      duration_minutes: duration, segment_count: segments, output_path: outputPath,
    });
    setJobId(jid);
  }

  function handleDone() {
    setBusy(false);
    loadGeneratedStory();
  }

  function sendToVoice() {
    window.location.href = `/voice?json=${encodeURIComponent(outputPath)}`;
  }

  return (
    <div className="flex flex-col md:h-screen md:overflow-hidden">
      {/* Header */}
      <div className="flex items-center justify-between px-4 md:px-6 py-3.5 border-b border-gray-800 shrink-0">
        <div className="flex items-center gap-3">
          <button onClick={() => setSidebarOpen(true)} className="md:hidden p-1 text-gray-400 hover:text-gray-200">
            <Menu size={18} />
          </button>
          <BookOpen size={18} className="text-gray-400" />
          <span className="text-sm font-semibold text-gray-100">Generate Story</span>
          <span className="text-xs text-gray-500 hidden md:block">AI builds a full story JSON from your title &amp; premise</span>
        </div>
        <div className="flex items-center gap-1.5 text-xs text-green-400">
          <span className="w-1.5 h-1.5 rounded-full bg-green-400" />
          Ready
        </div>
      </div>

      <div className="flex flex-col md:flex-row md:flex-1 md:overflow-hidden">
        {/* ── Left ─────────────────────────────────── */}
        <div className="flex flex-col w-full md:w-[58%] min-w-0 border-b md:border-b-0 md:border-r border-gray-800 md:overflow-hidden">
          <form onSubmit={submit} className="flex flex-col flex-1 overflow-hidden">
            <div className="flex-1 overflow-y-auto p-5 space-y-4">
              <Section num="01" title="The brief">
                <div>
                  <label className="label">Story title <span className="text-red-500">*</span></label>
                  <input className="input" value={title} onChange={e => setTitle(e.target.value)}
                    placeholder="e.g. The House on the Hill" required />
                </div>
                <div>
                  <label className="label">Premise / idea</label>
                  <textarea className="input resize-none" rows={4} value={premise} onChange={e => setPremise(e.target.value)}
                    placeholder="e.g. A family moves into an old house and discovers it has a dark history that refuses to stay buried…" />
                </div>
              </Section>

              <Section num="02" title="Shape">
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="label">Genre</label>
                    <select className="input" value={genre} onChange={e => setGenre(e.target.value)}>
                      {cfg?.genres.map(g => <option key={g}>{g}</option>)}
                    </select>
                  </div>
                  <div>
                    <label className="label">Language</label>
                    <select className="input" value={language} onChange={e => setLanguage(e.target.value)}>
                      {cfg?.languages.map(l => <option key={l}>{l}</option>)}
                    </select>
                  </div>
                </div>
                <div className="grid grid-cols-2 gap-4">
                  <div>
                    <div className="flex justify-between mb-1.5">
                      <span className="text-xs text-gray-400">Duration</span>
                      <span className="text-xs font-mono text-blue-400">{duration} min</span>
                    </div>
                    <input type="range" min={1} max={10} step={0.5} value={duration}
                      onChange={e => setDuration(+e.target.value)} className="w-full accent-blue-500 h-1" />
                  </div>
                  <div>
                    <div className="flex justify-between mb-1.5">
                      <span className="text-xs text-gray-400">Segments</span>
                      <span className="text-xs font-mono text-blue-400">{segments}</span>
                    </div>
                    <input type="range" min={3} max={12} step={1} value={segments}
                      onChange={e => setSegments(+e.target.value)} className="w-full accent-blue-500 h-1" />
                  </div>
                </div>
                <div>
                  <label className="label">Save JSON to</label>
                  <input className="input" value={outputPath} onChange={e => setOutputPath(e.target.value)} />
                </div>
              </Section>

              {jobId && (
                <div className="rounded-xl border border-gray-800 bg-gray-900/40 overflow-hidden">
                  <div className="px-4 py-3 border-b border-gray-800/60">
                    <span className="text-xs text-gray-500">Generation log</span>
                  </div>
                  <div className="p-4">
                    <LogStream jobId={jobId} onDone={handleDone} />
                  </div>
                </div>
              )}
            </div>

            <div className="p-5 border-t border-gray-800 shrink-0">
              <button type="submit" disabled={busy || !title.trim()}
                className="w-full flex items-center justify-center gap-2 rounded-xl bg-blue-600 py-3 text-sm font-semibold text-white hover:bg-blue-500 disabled:opacity-50 transition-colors shadow-lg">
                <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={1.5} d="M9.813 15.904L9 18.75l-.813-2.846a4.5 4.5 0 00-3.09-3.09L2.25 12l2.846-.813a4.5 4.5 0 003.09-3.09L9 5.25l.813 2.846a4.5 4.5 0 003.09 3.09L15.75 12l-2.846.813a4.5 4.5 0 00-3.09 3.09z" />
                </svg>
                {busy ? "Generating…" : "Generate Story JSON"}
              </button>
            </div>
          </form>
        </div>

        {/* ── Right: Story outline ─────────────────── */}
        <div className="flex flex-col w-full md:w-[42%] min-w-0 bg-gray-950">
          <div className="flex items-center justify-between px-5 py-3.5 border-b border-gray-800 shrink-0">
            <span className="text-sm font-semibold text-gray-200">Story outline</span>
            <div className="flex rounded-lg border border-gray-700 overflow-hidden text-xs">
              {(["outline", "json"] as OutlineView[]).map(v => (
                <button key={v} onClick={() => setOutlineView(v)}
                  className={`px-3 py-1 transition-colors capitalize ${outlineView === v ? "bg-blue-600 text-white" : "text-gray-400 hover:text-gray-200"}`}>
                  {v === "outline" ? "Outline" : "JSON"}
                </button>
              ))}
            </div>
          </div>

          <div className="flex-1 overflow-y-auto">
            {outlineView === "outline" ? (
              <div className="p-5 space-y-3">
                {/* Meta tags */}
                <div className="flex flex-wrap gap-2 items-center">
                  <span className="text-[10px] font-semibold tracking-wider bg-blue-600/20 text-blue-400 px-2 py-0.5 rounded uppercase">{displayOutline.genre}</span>
                  <span className="text-xs text-gray-500">{displayOutline.language}</span>
                  <span className="text-xs text-gray-500">~{displayOutline.durationMin} min · {displayOutline.segments.length} segments</span>
                </div>

                {/* Title + premise */}
                <div>
                  <h2 className={`text-xl font-bold mb-1.5 ${isDraft && !title ? "text-gray-600" : "text-gray-100"}`}>
                    {displayOutline.title}
                  </h2>
                  {displayOutline.premise && (
                    <p className="text-xs text-gray-500 leading-relaxed">{displayOutline.premise}</p>
                  )}
                </div>

                {/* Segment cards */}
                <div className="space-y-2 pt-1">
                  {displayOutline.segments.map(seg => (
                    <div key={seg.id} className="rounded-xl border border-gray-800 bg-gray-900/40 p-4">
                      <div className="flex items-start gap-3">
                        <span className="text-xs font-mono text-blue-400 shrink-0 mt-0.5">
                          {String(seg.id).padStart(2, "0")}
                        </span>
                        <div className="min-w-0">
                          <p className={`text-sm font-semibold mb-0.5 ${isDraft ? "text-gray-500" : "text-gray-200"}`}>
                            {seg.title}
                          </p>
                          {!isDraft && seg.description && (
                            <p className="text-xs text-gray-500 leading-relaxed">{seg.description}</p>
                          )}
                          {isDraft && (
                            <p className="text-xs text-gray-700 leading-relaxed">Placeholder — AI will fill this in</p>
                          )}
                        </div>
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            ) : (
              <div className="p-5">
                {generatedJson ? (
                  <pre className="text-[10px] font-mono text-gray-400 whitespace-pre overflow-x-auto leading-relaxed">
                    {generatedJson}
                  </pre>
                ) : (
                  <p className="text-xs text-gray-600 pt-8 text-center">JSON will appear here after generation.</p>
                )}
              </div>
            )}
          </div>

          {/* Footer */}
          <div className="border-t border-gray-800 px-5 py-3 flex items-center justify-between shrink-0">
            <div className="flex items-center gap-1.5 text-[10px] text-gray-600">
              <svg className="w-3 h-3 shrink-0" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11.049 2.927c.3-.921 1.603-.921 1.902 0l1.519 4.674a1 1 0 00.95.69h4.915c.969 0 1.371 1.24.588 1.81l-3.976 2.888a1 1 0 00-.363 1.118l1.518 4.674c.3.922-.755 1.688-1.538 1.118l-3.976-2.888a1 1 0 00-1.176 0l-3.976 2.888c-.783.57-1.838-.197-1.538-1.118l1.518-4.674a1 1 0 00-.363-1.118l-3.976-2.888c-.784-.57-.38-1.81.588-1.81h4.914a1 1 0 00.951-.69l1.519-4.674z" />
              </svg>
              {isDraft ? "Draft outline — regenerates on each run" : "Generated outline"}
            </div>
            <button
              onClick={sendToVoice}
              disabled={!generatedOutline}
              className="text-xs text-blue-400 hover:text-blue-300 disabled:text-gray-700 disabled:cursor-not-allowed transition-colors font-medium">
              Send to Voice →
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
